const { createTransporter } = require('../config/mail');
const dbFallback = require('../utils/dbFallback');

const sendContactMessage = async (contactData) => {
  const { name, email, message } = contactData;

  // 1. Save to DB (or local JSON fallback)
  let savedContact;
  try {
    savedContact = await dbFallback.saveContact({ name, email, message });
    console.log('Database save success: Contact message stored successfully.');
  } catch (dbError) {
    console.error('Database save failure: Failed to write contact message to database.', dbError);
    throw new Error('Database insertion failed: ' + dbError.message);
  }

  // 2. Initialize Nodemailer transporter
  const transporter = createTransporter();

  // 3. Verify SMTP transporter connection
  try {
    console.log('Attempting to verify SMTP transporter connection...');
    await transporter.verify();
    console.log('SMTP connection verified successfully.');
  } catch (verifyError) {
    console.error('SMTP connection verification failed. Stack trace:', verifyError);
    throw new Error('SMTP Connection Verification Failed: ' + verifyError.message);
  }

  const toEmail = process.env.CONTACT_TO_EMAIL || 'tharunummadala@gmail.com';

  const mailOptions = {
    from: `"Tharun Portfolio Bot" <${process.env.EMAIL_USER || 'no-reply@gmail.com'}>`,
    to: toEmail,
    subject: `New Portfolio Message from ${name}`,
    text: `You received a new message from your portfolio contact form:
    
Name: ${name}
Email: ${email}
Message: ${message}`,
    html: `
      <div style="font-family: Arial, sans-serif; padding: 20px; border: 1px solid #eaeaea; border-radius: 8px; max-width: 600px; background-color: #fafafa;">
        <h2 style="color: #ff2a2a; border-bottom: 2px solid #ff2a2a; padding-bottom: 10px;">New Portfolio Contact</h2>
        <p><strong>Name:</strong> ${name}</p>
        <p><strong>Email:</strong> <a href="mailto:${email}">${email}</a></p>
        <p><strong>Message:</strong></p>
        <blockquote style="background-color: #fff; padding: 15px; border-left: 4px solid #ccc; margin: 10px 0; line-height: 1.6;">
          ${message.replace(/\n/g, '<br>')}
        </blockquote>
        <hr style="border: 0; border-top: 1px solid #eee; margin-top: 20px;" />
        <p style="font-size: 0.8rem; color: #888;">This email was automatically generated by your portfolio server.</p>
      </div>
    `
  };

  // 4. Send email and throw error if it fails
  try {
    const info = await transporter.sendMail(mailOptions);
    console.log('Email send success: Message notification delivered.', info.messageId);
    return savedContact;
  } catch (emailError) {
    console.error('Email send failure: Failed to deliver SMTP notification. Stack trace:', emailError);
    throw new Error('SMTP Email Delivery Failed: ' + emailError.message);
  }
};

module.exports = {
  sendContactMessage
};
