const { createTransporter } = require('../config/mail');
const dbFallback = require('../utils/dbFallback');

const sendContactMessage = async (contactData) => {
  const { name, email, message } = contactData;

  // Save to DB (or local JSON fallback)
  const savedContact = await dbFallback.saveContact({ name, email, message });

  // Send email using Nodemailer config
  const transporter = createTransporter();
  const toEmail = process.env.CONTACT_TO_EMAIL || 'tharunummadala@gmail.com';

  const mailOptions = {
    from: `"Tharun Portfolio Bot" <${process.env.EMAIL_USER || 'no-reply@gmail.com'}>`,
    to: toEmail,
    subject: `New Portfolio Message from ${name}`,
    text: `You received a new message from your portfolio contact form:
    
Name: ${name}
Email: ${email}
Message: ${message}`,
    html: `
      <div style="font-family: Arial, sans-serif; padding: 20px; border: 1px solid #eaeaea; border-radius: 8px; max-width: 600px; background-color: #fafafa;">
        <h2 style="color: #ff2a2a; border-bottom: 2px solid #ff2a2a; padding-bottom: 10px;">New Portfolio Contact</h2>
        <p><strong>Name:</strong> ${name}</p>
        <p><strong>Email:</strong> <a href="mailto:${email}">${email}</a></p>
        <p><strong>Message:</strong></p>
        <blockquote style="background-color: #fff; padding: 15px; border-left: 4px solid #ccc; margin: 10px 0; line-height: 1.6;">
          ${message.replace(/\n/g, '<br>')}
        </blockquote>
        <hr style="border: 0; border-top: 1px solid #eee; margin-top: 20px;" />
        <p style="font-size: 0.8rem; color: #888;">This email was automatically generated by your portfolio server.</p>
      </div>
    `
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    console.log('Email sent:', info.messageId);
  } catch (emailError) {
    console.error('Nodemailer email notification failed to send:', emailError);
    // Fallback: database save succeeded, so we do not crash the request
  }

  return savedContact;
};

module.exports = {
  sendContactMessage
};
